"""Generate Korean glyph data (.dmp) + EA event for TMGC Korean patch.

Layout per glyph record (0x48 bytes, vanilla FE8 Glyph struct):
  +0  u32 next (0)
  +4  u8  hi byte of codepoint (informational)
  +5  u8  width (advance in px)
  +6  u16 pad
  +8  16 x u32 rows, 2bpp little-endian bit pairs (pixel x -> bits 2x..2x+1)
      values: 0 transparent, 2 ink, 3 outline/AA (matches vanilla convention)

Per font set, blocks are contiguous so the ASM hook uses arithmetic:
  [0]                syllables U+AC00..U+D7A3   (11172)
  [11172]            compat jamo U+3131..U+318E (94)
  [11266 + i]        extras (KRExtraTable order)

Two sets: dialogue (gulim.ttc 12px) and menu (gulim.ttc 11px).
"""
import os, struct, sys
from PIL import Image, ImageFont, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))

SYL_START, SYL_END = 0xAC00, 0xD7A3
JAMO_START, JAMO_END = 0x3131, 0x318E

# extra non-arithmetic chars (linear scan table in asm; keep < 120 entries)
EXTRAS = (
    "·"          # ·
    "–—"    # – —
    "‘’“”"  # ‘ ’ “ ”
    "•…"    # • …
    "、。"    # 、 。
    "〈〉《》「」『』【】"  # 〈〉《》「」『』【】
    "×○●★☆♪♥"  # × ○ ● ★ ☆ ♪ ♥
    "←↑→↓"  # ← ↑ → ↓
    "éèêüöä"  # é è ê ü ö ä (safety for names)
)

SETS = {
    # name: (font path, ttc index, px, baseline row for ink bottom, uniform_advance)
    'dialog': (r"C:\Windows\Fonts\gulim.ttc", 0, 12, 13, 12),
    'menu':   (r"C:\Windows\Fonts\gulim.ttc", 0, 11, 13, 11),
}


def render_char(font, ch, baseline):
    """Render ch, return (16x16 value grid, ink_width) or None if blank."""
    img = Image.new('L', (24, 24), 0)
    d = ImageDraw.Draw(img)
    d.text((2, 2), ch, fill=255, font=font)
    bbox = img.getbbox()
    grid = [[0] * 16 for _ in range(16)]
    if bbox is None:
        return grid, 0
    x0, y0, x1, y1 = bbox  # x1,y1 exclusive
    h = y1 - y0
    w = x1 - x0
    # place ink so bottom row = baseline, left col = 1
    dy = baseline - (y1 - 1)
    dx = 1 - x0
    for y in range(y0, y1):
        for x in range(x0, x1):
            if img.getpixel((x, y)) > 128:
                ty, tx = y + dy, x + dx
                if 0 <= ty < 16 and 0 <= tx < 16:
                    grid[ty][tx] = 2
    # outline: 8-neighbour halo of ink
    for y in range(16):
        for x in range(16):
            if grid[y][x] == 0:
                for ny in (y - 1, y, y + 1):
                    for nx in (x - 1, x, x + 1):
                        if 0 <= ny < 16 and 0 <= nx < 16 and grid[ny][nx] == 2:
                            grid[y][x] = 3
                            break
                    if grid[y][x]:
                        break
    return grid, w


def pack_glyph(grid, cp, adv):
    rows = []
    for y in range(16):
        v = 0
        for x in range(16):
            v |= (grid[y][x] & 3) << (2 * x)
        rows.append(v)
    return struct.pack('<IBBH16I', 0, (cp >> 8) & 0xFF, adv, 0, *rows)


def gen_set(name, cfg):
    path, idx, px, baseline, uni_adv = cfg
    font = ImageFont.truetype(path, px, index=idx)
    out = bytearray()
    chars = ([chr(c) for c in range(SYL_START, SYL_END + 1)] +
             [chr(c) for c in range(JAMO_START, JAMO_END + 1)] +
             list(EXTRAS))
    for ch in chars:
        cp = ord(ch)
        grid, w = render_char(font, ch, baseline)
        if SYL_START <= cp <= SYL_END:
            adv = uni_adv
        else:
            adv = min(15, w + 2) if w else uni_adv // 2 + 1
        out += pack_glyph(grid, cp, adv)
    fn = os.path.join(HERE, 'kr_%s.dmp' % name)
    open(fn, 'wb').write(out)
    print(name, len(chars), 'glyphs', len(out), 'bytes ->', fn)
    return chars


def gen_event():
    lines = []
    lines.append('// Auto-generated by gen_font.py - do not edit')
    lines.append('ALIGN 4')
    lines.append('KRGlyphs_Dialog:')
    lines.append('#incbin "kr_dialog.dmp"')
    lines.append('ALIGN 4')
    lines.append('KRGlyphs_Menu:')
    lines.append('#incbin "kr_menu.dmp"')
    lines.append('ALIGN 4')
    lines.append('KRExtraTable:')
    words = ' '.join('0x%04X' % ord(c) for c in EXTRAS)
    lines.append('SHORT %s 0x0000' % words)
    lines.append('ALIGN 4')
    open(os.path.join(HERE, 'KRFontData.event'), 'w').write('\n'.join(lines) + '\n')
    print('KRFontData.event written; extras:', len(EXTRAS))


def preview(name, cfg, text, outpng):
    path, idx, px, baseline, uni_adv = cfg
    font = ImageFont.truetype(path, px, index=idx)
    W = 16 * len(text)
    img = Image.new('P', (W, 16), 0)
    img.putpalette([220, 220, 220, 255, 255, 255, 40, 40, 40, 140, 140, 140] +
                   [0] * (252 * 3))
    x0 = 0
    for ch in text:
        grid, w = render_char(font, ch, baseline)
        for y in range(16):
            for x in range(16):
                v = grid[y][x]
                if v:
                    if 0 <= x0 + x < W:
                        img.putpixel((x0 + x, y), 2 if v == 2 else 3)
        x0 += uni_adv if SYL_START <= ord(ch) <= SYL_END else min(15, w + 2)
    img = img.convert('RGB').resize((W * 3, 48), Image.NEAREST)
    img.save(outpng)
    print('preview ->', outpng)


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'preview':
        preview('dialog', SETS['dialog'], '용사여, 검을 들어라! 「운명」의 아침이다.', os.path.join(HERE, 'preview_dialog.png'))
        preview('menu', SETS['menu'], '체력 힘 마력 기술 속도 행운 수비 저항', os.path.join(HERE, 'preview_menu.png'))
    else:
        gen_set('dialog', SETS['dialog'])
        gen_set('menu', SETS['menu'])
        gen_event()
